Feature/stateless auth
terragrids/api pull request #15
Opened 2022-10-03 12:55 UTC by cyleecode

Authentication middleware to validate /project endpoint using `Authorization` header and `walletAddress` header.

2022-10-12 21:03 UTC, lorenzopolidori requested changes

2022-10-12 21:03 UTC, lorenzopolidori commented on src/middleware/auth-handler.js
> +            decodedNote[0] === 'https://testnet.terragrids.org/' &&
This should be dependent on the environment:
```js
decodedNote[0] === `https://${env}.terragrids.org/`
```
where
```js
const env = process.env.ENV === 'dev' ? 'testnet' : 'app'
```

2022-10-13 09:06 UTC, cyleecode commented on src/app.js
> +app.use(requestLogger).use(errorHandler).use(authHandler).use(router.routes()).use(router.allowedMethods())
Fix with commit https://github.com/terragrids/api/pull/15/commits/4853f8b496b05315fc68ed27f0e1b4f1d83d5e68

2022-10-13 09:07 UTC, cyleecode commented on src/utils/auth-path.js
> +export const authenticatePath = ['/project']
Fix with https://github.com/terragrids/api/pull/15/commits/69e5ffe720f71b17bc8ce8c147afdf3f239f7a17

2022-10-13 09:11 UTC, cyleecode commented on src/middleware/auth-handler.js
> +        const accountId = ctx.headers?.walletaddress
Updated with https://github.com/terragrids/api/pull/15/commits/e913019eb5533e887889c15cf2f4219b5596a408

2022-10-13 09:12 UTC, cyleecode commented on src/middleware/auth-handler.js
> +            decodedNote[0] === 'https://testnet.terragrids.org/' &&
Pending to change dapp repo signToken note

2022-10-13 09:13 UTC, cyleecode commented on src/middleware/auth-handler.js
> +        //converting the base64 encoded tx back to binary data
https://github.com/terragrids/api/pull/15/commits/3bd128086ece6f318ef962aec95b5a31fb1b7c5e

2022-10-13 21:40 UTC, lorenzopolidori approved these changes

2022-10-13 21:41 UTC, merged